"""new

Revision ID: 93717ac13fee
Revises: 
Create Date: 2022-03-06 14:24:40.521162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93717ac13fee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
