"""update forum table

Revision ID: c7f60a3a5077
Revises: 21f5a275b979
Create Date: 2022-03-06 07:48:44.867651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7f60a3a5077'
down_revision = '21f5a275b979'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forum', sa.Column('description', sa.String(length=250), nullable=True))
    op.drop_column('forum', 'descrciption')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forum', sa.Column('descrciption', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.drop_column('forum', 'description')
    # ### end Alembic commands ###
